config/routes.rb
Ayadu::Application.routes.draw do
 

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins

 devise_for :users
 
  get "about" => "pages#about"  

  root "pins#index"

  match ":controller(/:action(/:id))",
  :via => [:get, :post]

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	 #using this http://stackoverflow.com/questions/7713695/how-to-modify-a-record-before-saving-on-ruby-on-rails
  #to prevent friendly id from becoming case insensitive sourcehttp://stackoverflow.com/questions/12673549/how-to-make-friendly-id-case-insensitive/12674241#12674241
  #before_create :downcase_stuff


     belongs_to :user
     has_many :orders
     has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }

     def self.search(query)
# where(:title, query) -> This would return an exact match of the query
	where("title like ?", "%#{query}%") 
	end

     	validates :title, presence: true
		validates :description, presence: true
		validates :image, presence: true
		validates :daily, numericality: true
		validates :weekly, numericality: true
		validates :monthly, numericality: true
		
	#private
    #def downcase_stuff
     # self.myfield.downcase!
     #end	

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only:[:edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json


  def index
    if params[:search]
    @pins = Pin.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    else

    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
   end
   end



 # def index
  # @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
 #end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :daily, :weekly, :monthly, :image)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", :cols => "10", :rows => "5" %>
  </div>
    <div class="form-group">
    <%= f.label :daily %>
    <%= f.text_field :daily, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :weekly %>
    <%= f.text_field :weekly, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :monthly %>
    <%= f.text_field :monthly, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">

        <strong><%= pin.title %></strong></br>
        <%= truncate(pin.description, :ommision => "... ", :length => 250) %><br/>
        

        <strong><%= pin.user.firstname if pin.user %></strong>
        <% if current_user && pin.user == current_user %>
        
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:large) %>
      </div>
      <div class="panel-body">
        <p><strong><%= @pin.title %></strong> by
        <strong><%= @pin.user.firstname if @pin.user %></strong></p>
        <p><%= @pin.description %></p>
         
        <strong>Rental</strong></br>
         Daily Rs:<strong><%= @pin.daily %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         Weekly Rs:<strong><%= @pin.weekly %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Monthly Rs:<strong> <%= @pin.monthly %></strong></br></br>



        <% if current_user && @pin.user == current_user %>
          <%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
      <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        <% end %>

      </div>
    </div>
  </div>

  <!--testing purposes-->
  <div class="col-md-4">

    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.user.avatar.url(:medium) %>
      </div>
      <div class="panel-body">
        
        <strong><%= @pin.user.firstname if @pin.user %></strong></p>
        <p><%= @pin.user.about %></p>


        <%if user_signed_in?%>
        <p><center><%= link_to "Send Request",new_order_path , class: "btn btn-primary btn-lg" %></center></p>
        <%else%>
        
        <p><center>
          <h2>To send request</h2>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
        </center></p>
        <%end%>
        
         
        

        

      </div>
    </div>
  </div>
</div>