config/routes.rb
Ayadu::Application.routes.draw do
 

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins

 devise_for :users
 
  get "about" => "pages#about"  

  root "pins#index"

  match ":controller(/:action(/:id))",
  :via => [:get, :post]

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Ayadu", root_path, :class=> "navbar-brand"%>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">

      <!-- search form code begins-->

        <form class="navbar-form navbar-left" role="search">
  <div class="form-group">

        <%= form_tag(pins_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Here", class: "form-control" %>
        </div>
        <%= submit_tag "Search", :class => "btn btn-default" %>
        <% end %>
        </form>


        <!-- search form code ends-->

      

      




        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Add Product
            <% end %>
          </li>


         <li><%= link_to "Account Settings", edit_user_registration_path %></li>
         <li><%=link_to "Log out", destroy_user_session_path, :method => :delete%></li>

          <!--<li><%= link_to "Log out", {:controller => "users", :action => "sign_out"}, method: :delete %></li>-->
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container-collapse -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ayadu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

	<%= render 'layouts/header' %>


     <div class="container">
     	<% flash.each do |name, msg| %>
    	 <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
          <%= yield %>
     </div>


</body>
</html>